# Generated by Django 3.2.5 on 2021-08-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
